[gcp_service_account]
type = "service_account"
project_id = "booktracker"
private_key_id = "ab5e97a9788c4b77df2827e85f8609a9f4021406"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcFHmq+KFUE8A/
HJcCmZfa7SwvZ9jKGyGfiuQKxvnohP9YT2W08VZUQtqBGZbgggalLWAQtYP3OVT/
VfeekWYPnJPT6osUaheGeLZm8VwnliQ376ISDtd9+ZNpVfbI0Rg3Pddmx7Pu2PLx
04Os84IpfyYHl73DdM4aHvAw1TMIF3N30jwRQca5Ch8HFIWhK76kINKb4SlRBedV
Sl8HszxorIMRwcU+p1CAOwNDWIPKKKQafUQPVQvz9Qdl+3o8Cyp/ddvIDagIxCAZ
BobpZ9UfwkCdfLSjzk7EobJkRNEQArz+LYR+/2sxKVYBjECpcujEKFZ0ljEdxQGg
zF3ePpqpAgMBAAECggEATK/zz3Awox/4wuUe98B2ikpPtbsdbxtyJWpb2SeJiIzj
fy23dowL9XOQOSEmElgsoZ0Elv3xHJIFPK4DiWUH59O7LUJSsUvgo7JneMqMvpyS
RU2Cr4EtdM+lHrTeOA6oPgOWDdHzsHw3d62o+fimN/h+03F8JeILOU3ji1iXHi+M
N3r70yc7lGPtuTRZdU5pcF8r7AbUG87b00EzspJPiFr97gmqL1QLSF5BMgB72oXz
QFcuuh2IeV1pjdqgcz56fEIs4Y8XmpIZnY9VB2iZwq4riyJxoPqZ66rznNIlGz2y
vEhNQSjqrbjhIugsszpH9r1A9ompOQ1QYKydTo8Y+wKBgQD271U1k8agTII7A/Xx
oKjuB1WwaMjTHEyTUOqlhhehYxRWSUuhYgAmepre/rr2Svqp+g+rrlMmj7d4bECY
hShQDVsdUnO92uyI7HyD1o6K1eA5P1m+vD0izerKKqqW+7ljUCejZWyesVy/dlng
ic6YeNIkZh8yPEPvMxoDwXFz5wKBgQDkKMNMVsK5YEcvP1hTRHOPjpProdCNGyMf
S2rzvWQueOyFtm8+TROmHQmYN5IJM0/KEMvcQ5yON5jwUM14ZCDR/wlOGQGC5IxO
jZGlJZuD0NkWEP6GU1DzNw5xn9u6ezV4K+mIua4bxpFqwPffztnHN3bde+tJWlrB
rp7GE0Sq7wKBgQDY5MdXVAF28zzAUW5JWfCHgnHFjYQ3yfeIvd4cnXdMDhbi42ZG
zimLos09aUkW5Czf+ACjr27hxAJHB+6FCRCrn8+UJcP70rtIWU/VDTQOxmU4Y2iU
nAqm829zO56zF09y6AipAIEzsl3g3jd7fg+05QrPZdOo8D5Lb/s9qT/ZqQKBgCWD
CjEH5rYBvVJoUMZH79P/dhR8o0Q/3PNtO+VdExaM7R5C02Fj3MIn7gbnxAvdMtYf
EtVhDGFZhLymHFIZ7Ed6bfY4KEZz+xmDLxn+5+WxNa/qFV7SXfHO8IH/7Wlojm72
kUvYc2a/q/LoTRiv8qBNXy6lDBcgUuGbKyGX02djAoGBAKnXPl6FzEcIiFJ+cHI4
n93S16h4LrAAy1Ohg9w4PW8L6aYrsk4Cn98dgYZRSOLepHOmJ7shADU86036wgSH
hztHDWVzmCNqyr7ubFwOu5sSZd8rj0h83EzwEYtmck++k8QdZctc2wpUWCKpx16X
ZfeAmVEXMgk9cH+Nqo8p8+hW\n-----END PRIVATE KEY-----"""
client_email = "booktracker-service@booktracker-475220.iam.gserviceaccount.com"
client_id = "102272142456766436077"
token_uri = "https://oauth2.googleapis.com/token"

[booktracker]
sheet_id = "1nnYvuKRAew48h6xXPgmQXxxgPzCjHMFiQwfBh0uQk7A"
covers_folder_id = "1m2J0ZkbVfHAQ61zOwsiGpHvjkQLgGQaw"

[oauth_client]
client_id = "419409632297-1568g05nqfm5cie97hhh9ke2751043dc.apps.googleusercontent.com"
client_secret = "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"
